// <auto-generated />
namespace Section4_And_5_ExerciseSolution_CodeFirst.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class EnhanceGenreTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EnhanceGenreTable));
        
        string IMigrationMetadata.Id
        {
            get { return "202310201340452_EnhanceGenreTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
